// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXkhRwJeFEYTFPjqk_zgNOL3RvBWjQjyA',
    appId: '1:397497516404:web:da4a4a98ce6e0bd1e06c21',
    messagingSenderId: '397497516404',
    projectId: 'recipe-app-9de78',
    authDomain: 'recipe-app-9de78.firebaseapp.com',
    storageBucket: 'recipe-app-9de78.appspot.com',
    measurementId: 'G-B9SYYPJVVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACKbVRhje4wbJT5eHTtBsLXV_93EUCIj8',
    appId: '1:397497516404:android:1df9dd93c1621432e06c21',
    messagingSenderId: '397497516404',
    projectId: 'recipe-app-9de78',
    storageBucket: 'recipe-app-9de78.appspot.com',
  );
}
